import type { HeaderCategory } from './types';

export const initialMockData: HeaderCategory[] = [
  {
    id: '1',
    name: 'Choose Game',
    isHidden: false,
    subItems: [
      { id: 's1', name: 'Indoor Mini Golf', icon: 'mini-golf', path: '/games/mini-golf', isHidden: false, cardDescription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s...' },
      { id: 's2', name: 'Duckpin Bowling', icon: 'bowling', path: '/games/bowling', isHidden: false, cardDescription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s...' },
      { id: 's3', name: 'Axe Throw', icon: 'axe', path: '/games/axe', isHidden: false, cardDescription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s...' },
      { id: 's4', name: 'AR Archery', icon: 'archery', path: '/games/archery', isHidden: false, cardDescription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s...' },
      { id: 's5', name: 'AR Darts', icon: 'darts', path: '/games/darts', isHidden: false, cardDescription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s...' },
      { id: 's6', name: 'Karaoke Dance', icon: 'karaoke', path: '/games/karaoke', isHidden: false, cardDescription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s...' },
    ]
  },
  {
    id: '2',
    name: 'Group Activities',
    isHidden: false,
    subItems: [
      {
        id: 'ga1',
        name: 'Birthday Parties',
        icon: '/icons/birthday.png',
        path: '/groups/birthday',
        isHidden: false,
        pageType: 'group-activity',
        pageHeadline: 'BOOM BIRTHDAYS',
        pageHeroImage: '',
        heroBookNowLink: '/book/birthday',
        sectionHeadline: "BATTLE IT OUT FOR A BIRTHDAY YOU WON'T FORGET",
        sectionDescription: 'Chat to our expert party planners today to plan the ultimate birthday get together. What does the price include?',
        checklistItems: [
          { id: 'cl1', title: '2 X GAMES', subtext: 'Choose from our epic selection of adrenaline pumping experiences' },
          { id: 'cl2', title: '2 X HOUSE DRINKS PER PERSON', subtext: 'Choose from a single spirit/mixer, house beer, wine or soft drinks!' },
          { id: 'cl3', title: 'THE SUPPORT OF OUR EXPERT PARTY PLANNING TEAM', subtext: '' },
          { id: 'cl4', title: 'BIRTHDAY PERSON BATTLES FREE', subtext: 'The birthday person goes free when you book this package! It\'s only right.' },
        ],
        howToBookHeadline: "HERE'S HOW TO BOOK",
        howToBookBody: "To book this package, either click here, email us on sales.consumer@boombattlebar.com or give us a call on 0207 286 0404.\n\nDon't worry, it's quick and easy. We promise not to keep you on the phone for hours!",
        howToBookLink: '/book/birthday',
        howToBookEmail: 'sales.consumer@boombattlebar.com',
        howToBookPhone: '0207 286 0404',
        chooseGamesHeading: 'CHOOSE YOUR GAMES',
        chooseGameIds: ['s1', 's2', 's3'],
      },
      {
        id: 'ga2',
        name: 'Team Up Parties',
        icon: '/icons/teamup.png',
        path: '/groups/team-up',
        isHidden: false,
        pageType: 'team-parties',
        pageHeadline: 'TEAM UP PARTIES',
        pageHeroImage: '',
        heroBookNowLink: '/book/team-up',
        sectionHeadline: 'EVENTS & ACTIVITIES',
        sectionDescription: 'Bring your team together for an unforgettable group experience. Choose your games, grab your drinks, and battle it out!',
        checklistItems: [
          { id: 'cl1', title: 'YOU GOT GAME? PROVE IT.', subtext: 'Take on your colleagues in a range of adrenaline-fuelled games' },
          { id: 'cl2', title: 'COMPETITIVE TEAM SCORING', subtext: 'Track your team scores across multiple games' },
          { id: 'cl3', title: 'DEDICATED EVENT HOST', subtext: 'Our hosts will keep the energy high all night long' },
        ],
        eventsDateHeading: 'EVENTS & ACTIVITIES MAY 24-26TH',
        featuredEvents: [
          {
            id: 'fe1',
            title: 'YOU GOT GAME? PROVE IT.',
            subtitle: 'ALL DAY, EVERYDAY.',
            description: 'From Axe Throwing to Shuffleboard and more, test your skills and bring the heat this long weekend! Rally your crew and let the games begin.',
            button1Text: 'BOOK MY BH GAMES',
            button1Link: '/book-bh-games',
            image: 'https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&q=80',
          },
          {
            id: 'fe2',
            title: 'SNOOKER',
            subtitle: '',
            description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
            button1Text: 'BOOK NOW',
            button1Link: '/book/snooker',
            button2Text: 'LEARN MORE',
            button2Link: '/games/snooker',
            image: 'https://images.unsplash.com/photo-1534158914592-062992fbe900?w=800&q=80',
          }
        ],
        howToBookHeadline: "HERE'S HOW TO BOOK",
        howToBookBody: "To book this package, either click here, email us on sales.consumer@boombattlebar.com or give us a call on 0207 286 0404.",
        howToBookLink: '/book/team-up',
        howToBookEmail: 'sales.consumer@boombattlebar.com',
        howToBookPhone: '0207 286 0404',
        chooseGamesHeading: 'CHOOSE YOUR GAMES',
        chooseGameIds: ['s1', 's2', 's3'],
      },
      {
        id: 'ga3',
        name: 'Boom Bundle',
        icon: '/icons/boombundle.png',
        path: '/groups/boom-bundle',
        isHidden: false,
        pageType: 'boom-bundle',
        heroHighlight: 'MORE BOOM FOR YOUR BUCK! BUNDLES FROM $27.50PP',
        pageHeadline: 'BOOM BUNDLES',
        heroSubtitle: 'Get more BOOM for your buck with our all-inclusive activity package. Available all week in Eastvale. each BOOM BUNDLE includes:',
        pageHeroImage: '',
        heroBookNowLink: '/book/boom-bundle',
        checklistItems: [
          { id: 'cl1', title: '1 X FULL LENGTH GAME', subtext: 'Choose from our epic range of games including Axe Throwing, Darts, and Mini Golf.' },
          { id: 'cl2', title: '2 PREMIUM DRINKS', subtext: 'Yep, including cocktails! Choose from cocktails, beers, or mocktails.' },
          { id: 'cl3', title: '2 STREET FOOD PLATES OR A BURGER', subtext: 'Finish off with our signature street food. Burgers, wings, and more.' },
        ],
        importantInfoHeading: 'BORING BUT IMPORTANT:',
        importantInfoText: 'After 7pm, it\'s over-18s only. Before then, under 18s are welcome when accompanied by an adult.\nMINIMUM 2 PEOPLE PER BOOKING SUN-WEDS AND 4 PEOPLE FRI-SAT.',
        bundleCards: [
          {
            id: 'bc1', title: 'INDOOR MINI GOLF BUNDLE', description: '', button1Text: 'BOOK NOW', button1Link: '/book/bundle-golf', button2Text: 'GAME INFO', button2Link: '/games/mini-golf', image: 'https://images.unsplash.com/photo-1518911710364-17ec553bde5d?w=800&q=80',
          },
          {
            id: 'bc2', title: 'DUCKPIN BOWLING BUNDLE', description: '', button1Text: 'BOOK NOW', button1Link: '/book/bundle-bowling', button2Text: 'GAME INFO', button2Link: '/games/bowling', image: 'https://images.unsplash.com/photo-1534158914592-062992fbe900?w=800&q=80',
          },
          {
            id: 'bc3', title: 'AXE THROW BUNDLE', description: '', button1Text: 'BOOK NOW', button1Link: '/book/bundle-axe', button2Text: 'GAME INFO', button2Link: '/games/axe', image: 'https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&q=80',
          }
        ],
        howToBookLink: '/book/boom-bundle',
        howToBookEmail: 'sales.consumer@boombattlebar.com',
        howToBookPhone: '0207 286 0404',
        chooseGamesHeading: 'CHOOSE YOUR GAMES',
        chooseGameIds: ['s1', 's2', 's3'],
      },
      {
        id: 'ga4',
        name: 'Queen Nights',
        icon: '/icons/queen.png',
        path: '/groups/queen-nights',
        isHidden: false,
        pageType: 'group-activity',
        pageHeadline: 'QUEEN NIGHTS',
        pageHeroImage: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80',
        heroBookNowLink: '/book/queens-night',
        sectionHeadline: 'CELEBRATE HER LAST FLING BEFORE THE RING WITH A BOOM',
        sectionDescription: 'Chat to our expert party planners today to plan a hen party full of fizz and fun. What does the price include?',
        checklistItems: [
          { id: 'cl1', title: '2 X GAMES', subtext: 'Choose from our epic selection adrenaline pumping experiences' },
          { id: 'cl2', title: '2 X HOUSE DRINKS PER PERSON', subtext: 'Choose from a single spirit/mixer, house beer, wine or soft drinks!' },
          { id: 'cl3', title: 'THE SUPPORT OF OUR EXPERT PARTY PLANING TEAM', subtext: '' },
          { id: 'cl4', title: 'QUEENS NIGHT FOR FREE', subtext: 'The Queen goes free when you book this package! It\'s only right.' },
        ],
        howToBookHeadline: "HERE'S HOW TO BOOK",
        howToBookBody: "To book this package, either click here, email us on USA@teamup.com or give us a call on 0207 286 0404. Don't worry, it's quick and easy. We promise not to keep you on the phone for hours!",
        statsBlocks: [
          { id: 'sb1', iconType: 'age', topText: 'AGE', mainText: '18+' },
          { id: 'sb2', iconType: 'price', topText: 'FROM', mainText: '$27.50', subText: 'PER PERSON\nMINIMUM 6 PEOPLE PER BOOKING' },
          { id: 'sb3', iconType: 'time', topText: 'FOR', mainText: '2-3', subText: 'HOURS' },
        ],
        otherGamesHeading: 'OTHER GAMES',
        otherGamesCards: [
          { id: 'og1', title: 'INDOOR MINI GOLF', description: '', button1Text: 'BOOK NOW', button1Link: '/book/golf', button2Text: 'LEARN MORE', button2Link: '/games/golf', image: 'https://images.unsplash.com/photo-1518911710364-17ec553bde5d?w=800&q=80' },
          { id: 'og2', title: 'DUCKPIN BOWLING', description: '', button1Text: 'BOOK NOW', button1Link: '/book/bowling', button2Text: 'LEARN MORE', button2Link: '/games/bowling', image: 'https://images.unsplash.com/photo-1534158914592-062992fbe900?w=800&q=80' },
          { id: 'og3', title: 'AXE THROW', description: '', button1Text: 'BOOK NOW', button1Link: '/book/axe', button2Text: 'LEARN MORE', button2Link: '/games/axe', image: 'https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&q=80' },
          { id: 'og4', title: 'AR ARCHERY', description: '', button1Text: 'BOOK NOW', button1Link: '/book/archery', button2Text: 'LEARN MORE', button2Link: '/games/archery', image: 'https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&q=80' },
          { id: 'og5', title: 'AR DARTS', description: '', button1Text: 'BOOK NOW', button1Link: '/book/darts', button2Text: 'LEARN MORE', button2Link: '/games/darts', image: 'https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&q=80' },
          { id: 'og6', title: 'KARAOKE DANCE', description: '', button1Text: 'BOOK NOW', button1Link: '/book/karaoke', button2Text: 'LEARN MORE', button2Link: '/games/karaoke', image: 'https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&q=80' },
        ]
      },
      {
        id: 'ga5',
        name: 'King Nights',
        icon: '/icons/king.png',
        path: '/groups/king-nights',
        isHidden: false,
        pageType: 'group-activity',
        pageHeadline: 'KING NIGHTS',
        heroBookNowLink: '/book/king-nights',
        sectionHeadline: "RULE THE NIGHT LIKE A KING",
        sectionDescription: "The ultimate lads\' night out — battle it out, claim your crown, and celebrate in style.",
        checklistItems: [
          { id: 'cl1', title: '2 X GAMES OF YOUR CHOICE', subtext: 'Compete in our most epic games' },
          { id: 'cl2', title: '2 X BEERS OR CIDERS PER PERSON', subtext: 'Fuel your competitive spirit' },
          { id: 'cl3', title: 'KING OF THE NIGHT AWARD', subtext: 'The top scorer takes the crown!' },
        ],
        howToBookHeadline: "HERE'S HOW TO BOOK",
        howToBookBody: "To book this package, either click here, email us on sales.consumer@boombattlebar.com or give us a call on 0207 286 0404.",
        howToBookLink: '/book/king-nights',
        howToBookEmail: 'sales.consumer@boombattlebar.com',
        howToBookPhone: '0207 286 0404',
        chooseGamesHeading: 'CHOOSE YOUR GAMES',
        chooseGameIds: ['s1', 's2', 's3'],
      },
      {
        id: 'ga6',
        name: 'Date Night',
        icon: '/icons/date.png',
        path: '/groups/date-night',
        isHidden: false,
        pageType: 'group-activity',
        pageHeadline: 'DATE NIGHT',
        pageHeroImage: '',
        heroBookNowLink: '/book/date-night',
        sectionHeadline: 'THE PERFECT DATE NIGHT OUT',
        sectionDescription: 'Skip the boring dinner and do something unforgettable. Challenge your date to a game — loser pays for drinks!',
        checklistItems: [
          { id: 'cl1', title: '2 X GAMES FOR 2 PEOPLE', subtext: 'Head-to-head action for you and your date' },
          { id: 'cl2', title: '1 X SHARING COCKTAIL PITCHER', subtext: 'Something sweet to share between you' },
          { id: 'cl3', title: 'ROMANTIC BOOTH SEATING', subtext: 'Subject to availability' },
        ],
        howToBookHeadline: "HERE'S HOW TO BOOK",
        howToBookBody: "To book this package, either click here, email us on sales.consumer@boombattlebar.com or give us a call on 0207 286 0404.",
        howToBookLink: '/book/date-night',
        howToBookEmail: 'sales.consumer@boombattlebar.com',
        howToBookPhone: '0207 286 0404',
        chooseGamesHeading: 'CHOOSE YOUR GAMES',
        chooseGameIds: ['s1', 's2', 's3'],
      },
      {
        id: 'ga7',
        name: 'Happy Hour',
        icon: '/icons/happy-hour.png',
        path: '/groups/happy-hour',
        isHidden: false,
        pageType: 'group-activity',
        pageHeadline: 'HAPPY HOUR',
        pageHeroImage: '',
        heroBookNowLink: '/book/happy-hour',
        sectionHeadline: "IT'S ALWAYS HAPPY HOUR AT BOOM",
        sectionDescription: 'Grab your crew and enjoy our incredible Happy Hour offers. Drinks deals meet epic games!',
        checklistItems: [
          { id: 'cl1', title: '50% OFF SELECTED DRINKS', subtext: 'Check your venue for specific Happy Hour times' },
          { id: 'cl2', title: 'WALK-IN WELCOME', subtext: 'No booking required for Happy Hour' },
          { id: 'cl3', title: 'ALL GAMES AVAILABLE', subtext: 'Full game menu available throughout Happy Hour' },
        ],
        howToBookHeadline: "HERE'S HOW TO BOOK",
        howToBookBody: "Just walk in during Happy Hour times! Or call us on 0207 286 0404 to reserve a spot.",
        howToBookLink: '/book/happy-hour',
        howToBookEmail: 'sales.consumer@boombattlebar.com',
        howToBookPhone: '0207 286 0404',
        chooseGamesHeading: 'CHOOSE YOUR GAMES',
        chooseGameIds: ['s1', 's2', 's3'],
      },
    ]
  },
  {
    id: '3',
    name: 'Bites & Drinks',
    isHidden: false,
    subItems: [
      {
        id: 'bd1',
        name: 'Drinks and Cocktails',
        icon: '/icons/drinks.png',
        path: '/bites-drinks/drinks',
        isHidden: false,
        pageType: 'game' // Or another type if needed
      },
      {
        id: 'bd2',
        name: 'Street Food',
        icon: '/icons/food.png',
        path: '/bites-drinks/food',
        isHidden: false,
        pageType: 'game'
      }
    ]
  },
  {
    id: '4',
    name: 'Corporates',
    isHidden: false,
    subItems: []
  }
];
